### ISSUE TITLE
Can't get default project to run

### ISSUE THREAD

**Issue by JavaLeg** [JavaLeg/Project-DC#2]
Running should simply create a window with the _BadLogic_ title. However get this error instead!!

`	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:147)
	at com.badlogic.gdx.graphics.TextureData$Factory.loadFromFile(TextureData.java:98)
	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:100)
	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:92)
	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:88)
	at com.maindc.DC_Main.create(DC_Main.java:16)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: File not found: badlogic.jpg (Internal)
	at com.badlogic.gdx.files.FileHandle.read(FileHandle.java:136)
	at com.badlogic.gdx.files.FileHandle.readBytes(FileHandle.java:222)
	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:144)
	... 7 more`

**Comment by JavaLeg** [comment]
gg reported. 

https://stackoverflow.com/questions/22822767/file-not-found-when-running-new-libgdx-project/22833470

**Comment by JavaLeg** [comment]
![fix](https://user-images.githubusercontent.com/30682722/30578237-2bb7423a-9d56-11e7-864f-4333333f7a93.png)

**Comment by MatthewC221** [comment]
Nice!
